site_name: EverCas
site_description: 'Cloneable (with rclone) content-addressable storage for Python'
repo_url: https://github.com/weedonandscott/evercas
theme: readthedocs

plugins: 
  - search
  - mkdocstrings
